
# Configurações do CMS
media_folder: "assets/img"  # Caminho onde as imagens serão armazenadas
public_folder: "/assets/img"  # Caminho público para as imagens

# Incluindo a pasta img-destaques
featured_media_folder: "assets/img/img-destaques"  # Caminho para imagens em destaque

# Produtos em Destaque
featured_products:
  - product_image: "/assets/img/produto1.png"
    product_description: "Descrição do Produto 1"
  - product_image: "/assets/img/produto2.png"
    product_description: "Descrição do Produto 2"
  - product_image: "/assets/img/produto3.png"
    product_description: "Descrição do Produto 3"

# Configurações Gerais
title: "Título do Seu Site"
logo: "/assets/img/logo.png"  # Caminho da logo da empresa
promotion: "/assets/img/promocao.png"  # Caminho da imagem de promoção

# Seção de Encomenda
tituloEncomenda: "Faça sua encomenda conosco"
textoEncomenda: "Não achou o que procurava? Não se preocupe! Fale conosco que vamos atrás do que precisa."
linkWhatsApp: "https://wa.me/5562994953404"  # Link para o WhatsApp
iconeWhatsApp: "/assets/img/icons8-whatsapp.svg"  # Caminho do ícone do WhatsApp

# Regras de Entregas
tituloEntregas: "Regras de Entregas"
regrasEntregas: "Nossa entrega é feita em toda a cidade de Jaraguá-GO para compras acima de R$ 100. Para compras menores, será cobrada uma taxa de R$ 5!"

# Formas de Pagamento
tituloPagamentos: "Formas de Pagamento"
iconeVisa: "/assets/img/visa.png"  # Caminho do ícone Visa
iconeCartao: "/assets/img/card.png"  # Caminho do ícone de cartão
informacaoPagamento: "Dividimos em até 6x nos cartões"
iconePix: "/assets/img/icons8-pix-48.png"  # Caminho do ícone Pix
informacaoPix: "No Pix desconto de até 10%"

# Seção de Contato
tituloFaleConosco: "Fale Conosco"
linkInstagram: "https://www.instagram.com/xico__multimarcas"  # Link do Instagram
iconeInstagram: "/assets/img/icons8-instagram.svg"  # Caminho do ícone Instagram
linkEndereco: "https://www.google.com.br/maps/place/Xico+Multimarcas"  # Link do Google Maps
iconeEndereco: "/assets/img/addresswhite.png"  # Caminho do ícone de endereço
endereco: "R. Creso Gomes, 85 - Qd19 Lt28 - Vila Sao Jose, Jaraguá - GO, 76330-000"


