backend:
  name: git-gateway
  branch: main # Defina a branch principal que você está usando

media_folder: "assets/img-destaques" # Caminho para armazenar as imagens no repositório
public_folder: "/assets/img-destaques" # Caminho público para acessar as imagens

media_library:
  name: uploadcare # Você pode mudar para 'uploadcare' ou deixar como está, se estiver configurando algo diferente

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "content/produtos" # Certifique-se de que esse diretório exista
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título do Produto", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Imagem do Produto", name: "product_image", widget: "image" }
      - { label: "Preço", name: "price", widget: "number" }

  - name: "promocoes"
    label: "Promoções"
    folder: "content/promocoes" # Certifique-se de que esse diretório exista
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Promoção", name: "promotion", widget: "string" }
      - { label: "Imagem da Promoção", name: "promotion_image", widget: "image" }

  - name: "configuracoes"
    label: "Configurações do Site"
    folder: "content/configuracoes" # Use 'folder' em vez de 'file' para coleções que devem ter múltiplos arquivos
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título do Site", name: "title", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Link do WhatsApp", name: "linkWhatsApp", widget: "string" }
      - { label: "Regras de Entregas", name: "regrasEntregas", widget: "text" }
      - { label: "Informações de Pagamento", name: "informacaoPagamento", widget: "text" }
      - { label: "Informações do Pix", name: "informacaoPix", widget: "text" }
