backend:
  name: github
  repo: seu-usuario/seu-repositorio # substitua com seu repositório
  branch: main # ou o branch que você estiver usando

media_folder: "assets/img" # Onde as imagens serão armazenadas
public_folder: "/assets/img" # Caminho público para as imagens

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts" # pasta onde seus posts são armazenados
    create: true
    delete: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Publicar", name: "published", widget: "boolean", default: true }

# Opções de configuração adicional
site_url: "https://catalogoxicomultimarcas.netlify.app" # Substitua pelo URL do seu site
display_url: "https://catalogoxicomultimarcas.netlify.app/#/" # URL que será exibido no CMS
