backend:
  name: github
  repo: victornataneu/sitexico # substitua com seu repositório
  branch: main

media_folder: "assets/img" # Onde as imagens serão armazenadas
public_folder: "/assets/img" # Caminho público para as imagens

collections:
  - name: "posts"
    label: "Posts"
    folder: "folder" # pasta onde os posts estão armazenados (ajustado para "folder")
    create: true
    delete: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Publicar", name: "published", widget: "boolean", default: true }

site_url: "https://catalogoxicomultimarcas.netlify.app" # Substitua pelo URL do seu site
display_url: "https://catalogoxicomultimarcas.netlify.app/#/"
