backend:
  name: git-gateway
  branch: main  # ou master, dependendo do seu repositório

media_folder: "assets/img"
public_folder: "/assets/img"

# Incluindo a pasta img-destaques
featured_media_folder: "assets/img-destaques"  # Caminho para imagens em destaque

collections:
  # Produtos em Destaque
  - name: "featured_products"
    label: "Produtos em Destaque"
    folder: "featured_products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Imagem do Produto", name: "product_image", widget: "image" }
      - { label: "Descrição do Produto", name: "product_description", widget: "string" }

  # Seção de Encomenda
  - name: "encomenda"
    label: "Seção de Encomenda"
    folder: "content/encomenda"
    create: false
    fields:
      - { label: "Título", name: "tituloEncomenda", widget: "string" }
      - { label: "Texto", name: "textoEncomenda", widget: "text" }
      - { label: "Link WhatsApp", name: "linkWhatsApp", widget: "string" }
      - { label: "Ícone WhatsApp", name: "iconeWhatsApp", widget: "image" }

  # Regras de Entregas
  - name: "regras_entregas"
    label: "Regras de Entregas"
    folder: "content/regras_entregas"
    create: false
    fields:
      - { label: "Título", name: "tituloEntregas", widget: "string" }
      - { label: "Regras", name: "regrasEntregas", widget: "text" }

  # Formas de Pagamento
  - name: "pagamentos"
    label: "Formas de Pagamento"
    folder: "content/pagamentos"
    create: false
    fields:
      - { label: "Título", name: "tituloPagamentos", widget: "string" }
      - { label: "Ícone Visa", name: "iconeVisa", widget: "image" }
      - { label: "Ícone Cartão", name: "iconeCartao", widget: "image" }
      - { label: "Informação Cartão", name: "informacaoPagamento", widget: "text" }
      - { label: "Ícone Pix", name: "iconePix", widget: "image" }
      - { label: "Informação Pix", name: "informacaoPix", widget: "text" }

  # Contato
  - name: "contato"
    label: "Seção de Contato"
    folder: "content/contato"
    create: false
    fields:
      - { label: "Título", name: "tituloFaleConosco", widget: "string" }
      - { label: "Link Instagram", name: "linkInstagram", widget: "string" }
      - { label: "Ícone Instagram", name: "iconeInstagram", widget: "image" }
      - { label: "Link Endereço", name: "linkEndereco", widget: "string" }
      - { label: "Ícone Endereço", name: "iconeEndereco", widget: "image" }
      - { label: "Endereço", name: "endereco", widget: "text" }
