backend:
  name: git-gateway
  branch: main  # Substitua pelo nome da branch que você está usando, se necessário

media_folder: "assets/img"  # Pasta onde as imagens serão armazenadas
public_folder: "/assets/img"  # Caminho público para as imagens

collections:
  - name: "produtos"  # Nome da coleção
    label: "Produtos"  # Label a ser exibida no CMS
    folder: "produtos"  # Pasta onde os produtos estão armazenados
    create: true
    slug: "{{slug}}"  # Usado para gerar URLs amigáveis
    fields:
      - { label: "Nome", name: "nome", widget: "string" }
      - { label: "Descrição", name: "descricao", widget: "text" }
      - { label: "Imagem", name: "imagem", widget: "image" }
