backend:
  name: git-gateway
  branch: main # substitua pelo nome da branch que você está usando

media_folder: "assets/uploads" # pasta para uploads de imagens
public_folder: "/assets/uploads" # caminho público para a pasta de uploads

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
