backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "conteudo"
    label: "Conteúdo do Site"
    folder: "folder"
    create: true
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Conteúdo", name: "conteudo", widget: "markdown" }
      - { label: "Imagem", name: "imagem", widget: "image" }

  - name: "html"
    label: "Páginas HTML"
    folder: "." 
    create: false 
    fields:
      - { label: "Arquivo", name: "file", widget: "file", required: true, format: "html" }

  - name: "principal"
    label: "Página Principal"
    folder: "folder"  # Diretório para a página principal
    create: false
    fields:
      - { label: "Título Principal", name: "titulo_principal", widget: "string" }
      - { label: "Texto Principal", name: "texto_principal", widget: "text" }
      - { label: "Imagem de Destaque", name: "imagem_destaque", widget: "image" }
      - { label: "Carrossel de Imagens", name: "carrossel", widget: "list", fields: [{label: "Imagem", name: "imagem", widget: "image"}] }
