backend:
  name: git-gateway
  branch: main  # Certifique-se de que este é o branch correto

media_folder: "assets/uploads"  # Diretório para uploads de mídia
public_folder: "/assets/uploads"  # Diretório público para acesso às mídias

collections:
  - name: "conteudo"
    label: "Conteúdo do Site"
    folder: "folder"  # Diretório onde os arquivos de conteúdo são armazenados
    create: true  # Permite a criação de novos arquivos
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Conteúdo", name: "conteudo", widget: "markdown" }
      - { label: "Imagem", name: "imagem", widget: "image" }

  - name: "html"
    label: "Páginas HTML"
    folder: "."  # A pasta raiz do repositório
    create: false  # Não queremos criar novos arquivos HTML
    fields:
      - { label: "Arquivo", name: "file", widget: "file", required: true, format: "html" }
